env:
  global:
    - CC_TEST_REPORTER_ID=49dd4a271d055fb567d50b3482f1adcd33598e59ce18ff78e84312bb08bb6270
language: node_js
node_js:
  - "node"
cache: yarn
install:
  - npm install -g codecov
after_success:
  - yarn run coverage
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: uhN3Ri4kuRuP8BRbEWml6cSR2reOnxiirCmX9PYsxq8KGer0TGFroMn6LKcIYiBcjHye/z0qxLp6SkWq1ZNpZI3+yNZ1lNckq0t/lCNldccSjNyA5XmK/irnS+i5zzezbrmi9YzOooAJ/HSfpYeEIqv8+kpbIV51BwTGQSECnz6KyyeZb4kstLfchToQUOkdjYxKqAvP6IHuhSS3vZqYMxbN+oOzf8V3rFFsxnBcu0J8R26yjQChB81hR3gBLqp2uhw/3L9ac4mCo7NwCArMRW3z4lzwbUdIiVC/sKsWmuNzTmQZ9VrnZVjcX8B8cSLZsYvwJ+qmQv2xO6zknFo3Ws+ZUs1FkkIg0YIH7dJ1FuHxzXqFQjmMKKcrosb07dNOqXHC9zvXal/B/ma/Nbo+6hvjsPL8eFRa9SJL6/zloA+BjpyBqYNCEPO7YvR4eshR5yoxlxbn1pKYgOy4dAaoEBXFshImqM4zrreZAe4yl1SF/AHgA5TL0d2T/ImrzEK3BIn3vzkhA2ikLDhGAecMvTRB4fxFaUAHyZ21q/XVANIQYUwEcFdmVvmtCa3ZTvjhdPd4WQNlNO8BDZTHliJtynrxtHJ968RBxlF6fmvG8cfjsPUu96JRKvMv0ip1Oucdq1RaSN3ojmtQNAOXGWfJNqJTZqoac40NfPLy4yBWrdU=
